apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
spec:
  type: NodePort
  selector:
    app: mi-app
  ports:
    - protocol: TCP
      port: 80  # Puerto del Service
      targetPort: 80  # Debe coincidir con el puerto del contenedor (EXPOSE 80 en Dockerfile)