# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048  
  end
  config.vm.network "private_network", ip: "192.168.56.0"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../site.yml"
  end
end

